<a href="https://colab.research.google.com/github/Kggzzz/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ที่เรียนไปแล้วมี 1 ตัวคือ list หน้าตาประมาณนี้

{แนบรูป}

#Dictionary

สามารถ index เก็บด้วยอะไรก็ได้ ไม่จำเป็นต้องเป็น 0,1,2,3,... พอไม่ได้เก็บด้วยตัวเลขจะทำให้เราไม่รู้ลำดับข้อมูล ทำให้ลำดับหายไป 

In [1]:
ex_dict = {'a':10,'1':1,'stat':5} #curly bracket ในการบอกว่าเป็น dict
#ตัวหน้าคือตัวชี้ เวลาในการหาข้อมูล

In [2]:
ex_dict['stat']

5

In [3]:
ex2_dict = {1:'one',2:'two',3:'three'}

In [4]:
ex2_dict[2]

'two'

การเพิ่มสมาชิก

In [5]:
ex2_dict[0] = 'zero' #เพิ่มค่าเข้าไปใน dict 

In [6]:
ex2_dict[0]

'zero'

คำสั่ง

In [7]:
ex2_dict.keys() #เป็นการดูว่า dict นี้มีตัว index อะไรบ้าง

dict_keys([1, 2, 3, 0])

In [8]:
#วนลูปเพื่อให้ปิด index ที่ละตัว
for index in ex2_dict.keys() : #ตัวหน้าเรียก keys ตัวหลังเรียกว่า value
  print(index)

1
2
3
0


In [9]:
ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

###Dict จะเอาไปใช้ร่วมกับ Dataframe ของ Pandas 

###Numpy คือ package ที่ทำงานเกี่ยวกับ array ของตัวเลข (ที่มีคนเขียนขึ้นมาแล้วนิยมใช้กัน)

Numpy -> number python

In [10]:
import numpy as np
#วิธีเรียกใช้งาน packet ของ numpy

In [43]:
ex_2d_array = np.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array) #เป็นการส้รางเมททริกตัวตนเอง

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


การชี้ค่าใน numpy array 

In [44]:
ex_2d_array[1,2]

0.3

In [45]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #การชี้ list

list_x[1][2] #ดูลำดับใน list อยากเห็นตัวไหนก็เลือก เมททริกก่อนแล้วค่อยเลือกตัวในเมททริก

0.3

Operations

In [46]:
ex2_2d_array = np.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [47]:
ex_2d_array.shape #ตรวจสอบขนาดของ matrix 

(2, 3)

In [48]:
ex_2d_array + ex2_2d_array #matrix แถวบวกแถว หลักบวกหลัก

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [49]:
ex_2d_array - ex2_2d_array

array([[ 4.2,  3. ,  4.5],
       [ 9.1,  0.1, -0.7]])

In [50]:
#ทดลองนำ matrix ที่อยู่ใน list มาบวกกัน
list_x = [[5.2,3.0,4.5],[9.1,0.1,3.0]]
list_x2 = [[1,0,0],[0,0,1]]

list_x + list_x2 #list จะต่อกัน 

[[5.2, 3.0, 4.5], [9.1, 0.1, 3.0], [1, 0, 0], [0, 0, 1]]

In [51]:
ex_2d_array * ex2_2d_array 
#โดยวิธีการคูณแบบ array จะเป็นการเอาต่ำแหน่งเดียวกันมาคูณกัน

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

##Matix multiplication (dot product)

In [52]:
np.dot(ex_2d_array,ex2_2d_array.T) #เราจะ transpote กลับแถวเป็นหลัก 1 ตัวเพื่อให้คูณกันได้
#matrix คูณกัน แถวคูณหลัก (เงื่อนไขคือหลักของตัวหน้าต้องเท่ากับแถวของตัวหลัง)

array([[5.2, 4.5],
       [9.1, 0.3]])

In [53]:
print(ex_2d_array)
print(ex2_2d_array.T)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[1 0]
 [0 0]
 [0 1]]


In [54]:
dot_mat = np.dot(ex_2d_array,ex2_2d_array.T)
print(dot_mat)

[[5.2 4.5]
 [9.1 0.3]]


In [55]:
np.linalg.det(dot_mat)

-39.389999999999986

Search google -> stackoverflow หรือ web ของ package สำหรับ operations อื่นๆ

Matrix slicing 

#HW 5 
###ห้ามใช้ funtion array , numpy 